Deprecate repository databiosphere/azul#2897
HumanCellAtlas/dcp-cli pull request #526
Opened 2021-03-23 17:17 UTC by amarjandu

2021-03-23 17:27 UTC, amarjandu commented
I performed the deprecation testing on https://pypi.org/project/dbio-cli/. version 1.0.0 is a known good build, version 1.5.5 is the version that fails when you try to install.

2021-03-25 00:04 UTC, danielsotirhos approved these changes
Should `databiosphere/azul#2897` be in the title? Seems like it should be a link in a comment instead.

Approved.

```
(.venv) daniel@Crispin ~/dcp-cli $ pip install git+https://github.com/HumanCellAtlas/dcp-cli.git@issues/amar/2897-RIP-cli
Collecting git+https://github.com/HumanCellAtlas/dcp-cli.git@issues/amar/2897-RIP-cli
  Cloning https://github.com/HumanCellAtlas/dcp-cli.git (to revision issues/amar/2897-RIP-cli) to /private/var/folders/8s/9dwlx2rj1n39n7mdk610dhj40000gn/T/pip-req-build-3qrgv4vs
  Running command git clone -q https://github.com/HumanCellAtlas/dcp-cli.git /private/var/folders/8s/9dwlx2rj1n39n7mdk610dhj40000gn/T/pip-req-build-3qrgv4vs
  Running command git checkout -b issues/amar/2897-RIP-cli --track origin/issues/amar/2897-RIP-cli
  Switched to a new branch 'issues/amar/2897-RIP-cli'
  Branch 'issues/amar/2897-RIP-cli' set up to track remote branch 'issues/amar/2897-RIP-cli' from 'origin'.
  Running command git submodule update --init --recursive -q
    ERROR: Command errored out with exit status 1:
     command: /Users/daniel/dcp-cli/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8s/9dwlx2rj1n39n7mdk610dhj40000gn/T/pip-req-build-3qrgv4vs/setup.py'"'"'; __file__='"'"'/private/var/folders/8s/9dwlx2rj1n39n7mdk610dhj40000gn/T/pip-req-build-3qrgv4vs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/8s/9dwlx2rj1n39n7mdk610dhj40000gn/T/pip-req-build-3qrgv4vs/
    Complete output (3 lines):

    The HCA module is deprecated, for assistance with accessing data please refer to the data-browser quick start guide at https://data.humancellatlas.org/guides/quick-start-guide

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

2021-03-25 00:04 UTC, danielsotirhos commented on setup.py
> +if not any(arg in sys.argv for arg in ('sdist', 'bdist_wheel', '--name', '--version')):
```suggestion
if set(sys.argv).isdisjoint({'sdist', 'bdist_wheel', '--name', '--version'})
```
This might read a little easier.

2021-03-25 00:06 UTC, amarjandu commented on setup.py
> +if not any(arg in sys.argv for arg in ('sdist', 'bdist_wheel', '--name', '--version')):
Thanks! I'll implement this.

2021-03-25 17:12 UTC, amarjandu commented
@danielsotirhos having the issue link the in PR title is wrong (I did not change it from the default oops), I wanted the link to be only within the commit message. 

![Uploading Screen Shot 2021-03-25 at 10.03.28 AM.png…]()

I'm all for removing it from the commit message, but it does seem useful to have. 

I'll leave it within the commit message for now, and @hannes-ucsc so he can 👀

2021-03-25 17:22 UTC, hannes-ucsc requested changes

2021-03-25 17:22 UTC, hannes-ucsc commented on README.rst
> +This repository is deprecated, for assistance with accessing data please refer to the `data-browser quick start guide. <https://data.humancellatlas.org/guides/quick-start-guide>`_
```suggestion
This repository has been deprecated. For information about accessing Human Cell Atlas data please refer to the `data-browser quick start guide. <https://data.humancellatlas.org/guides/quick-start-guide>`_
```

2021-03-25 17:22 UTC, hannes-ucsc commented on setup.py
> +    sys.exit('\nThe HCA module is deprecated, for assistance with accessing data '
Like above.

2021-03-30 20:49 UTC, merged